name: Build
on:
  push:
    branches: ["master", "ci"]
  pull_request:
    branches: ["master"]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: sudo apt update && sudo apt install --yes libgtest-dev librtmp-dev
      - name: make
        run: make -C ui/linux
      - name: make
        run: make -C ui/linux Peercast_YT-x86_64.AppImage
      - name: test
        run: make -C ui/linux/tests && cd ui/linux/tests && ./test-all && cd ../../../bvt && cp -R ../ui/linux/peercast-yt . && ruby test-all.rb
      - name: release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            ./src-tauri/target/release/bundle/msi/*.msi
            *.zip
      - name: Upload linux binary directory
        uses: actions/upload-artifact@v3
        with:
          name: directory
          path: ui/linux/peercast-yt
      - name: Upload linux binary
        uses: actions/upload-artifact@v3
        with:
          name: tgz
          path: ui/linux/peercast-yt-linux-x86_64.tar.gz
      - name: Upload AppImage
        uses: actions/upload-artifact@v3
        with:
          name: AppImage
          path: ui/linux/Peercast_YT-x86_64.AppImage
